todo-rails/config/routes.rb
Rails.application.routes.draw do

  resources :tenants do
    resources :todo_items
  end

  root 'todo#index'

end

todo-rails/app/models/tenant.rb
class Tenant < ActiveRecord::Base
  validates :name, presence: true
  has_many :todo_items
end

todo-rails/app/models/todo_item.rb
class TodoItem < ActiveRecord::Base

  validates :title, presence: true, length: { minimum: 2 }
  validates :due_date, presence: true

  validate :valid_date?, if: 'due_date.present?'

  def valid_date?
    unless Chronic.parse(due_date)
      errors.add(:due_date, "date is invalid")
    end
  end

end

todo-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo-rails/app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def index
    @tenants = Tenant.all
  end

  def show
    @tenant = Tenant.find(params[:id])
  end

  def new
  end

  def create
    @tenant = Tenant.new(tenant_params)

    @tenant.save
    redirect_to @tenant
  end

  private
    def tenant_params
      params.require(:tenant).permit(:name)
    end

end

todo-rails/app/controllers/todo_controller.rb
class TodoController < ApplicationController
  def index
  end
end

todo-rails/app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    @tenant = Tenant.find(params[:tenant_id])
    render json: @tenant.todo_items
  end

  def show
    @todo_item = TodoItem.find(params[:id])
  end

  def new
    @todo_item = TodoItem.new
  end

  def edit
    @todo_item = TodoItem.find(params[:id])
  end

  def create
    @tenant = Tenant.find(params[:tenant_id])
    @todo_item = @tenant.todo_items.create(todo_item_params)

    if @todo_item.valid?
      render json: @tenant.todo_items
    else
      render json: {errors: @todo_item.errors}, status: :unprocessable_entity
    end

  end

  def update
    @tenant = Tenant.find(params[:tenant_id])
    @todo_item = @tenant.todo_items.find(params[:id])

    @todo_item.update(todo_item_params)

    render json: @tenant.todo_items
  end

  def destroy
    @tenant = Tenant.find(params[:tenant_id])
    @todo_item = @tenant.todo_items.find(params[:id])
    @todo_item.destroy

    render json: @tenant.todo_items
  end

  private
    def todo_item_params
      params.require(:todo_item).permit(:title, :due_date)
    end
end

todo-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

todo-rails/app/helpers/tenants_helper.rb
module TenantsHelper
end

todo-rails/app/helpers/todo_helper.rb
module TodoHelper
end

todo-rails/app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

todo-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To do</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

todo-rails/app/views/tenants/index.html.erb
<div class="container">
  <h1>Participants</h1>
  <br />
  <div class="row">
    <div class="col-md-6">
      <table class="table table-striped">
        <tr>
          <th>Name</th>
          <th>Id</th>
          <th>Link</th>
        </tr>

        <% @tenants.each do |tenant| %>
            <tr>
              <td><%= tenant.name %></td>
              <td><%= tenant.id %></td>
              <td><%= link_to 'Show', tenant_path(tenant) %></td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

todo-rails/app/views/tenants/new.html.erb
<div class="container",  style="max-width:600px;",>

  <%= form_for :tenant, url: tenants_path do |f| %>
      <h1>Please sign in</h1>
      <br />

      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name, :class => "form-control" %>
      </p>
      <p>
        <%= f.submit 'Go', :class =>"btn btn-lg btn-primary" %>
      </p>
  <% end %>

</div>

todo-rails/app/views/tenants/show.html.erb
<div style="background-color: #e5e5e5;padding:20px">
  <div class="container">
    <h3> <%= @tenant.name %> </h3>
    <h3> id: <%= @tenant.id %> </h3>

    <br />

    <div class="list-group">
      <p class="list-group-item active">API</p>
      <p class="list-group-item">GET:  /tenants/<%=@tenant.id %>/todo_items</p>
      <p class="list-group-item">POST: /tenants/<%=@tenant.id %>/todo_items</p>
      <p class="list-group-item">PUT:  /tenants/<%=@tenant.id %>/todo_items/{item_id}</p>
      <p class="list-group-item">DELETE: /tenants/<%=@tenant.id %>/todo_items/{item_id}</p>
    </div>
  </div>
</div>

<div class="container">
  <h3>Add a todo item</h3>

  <%= form_for([@tenant, @tenant.todo_items.build]) do |f| %>
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :due_date %><br>
        <%= f.text_field :due_date %>
      </p>
      <p>
        <%= f.submit 'Add item' , :class =>"btn btn-lg btn-primary" %>
      </p>
  <% end %>
</div>

<br />
<br />

<div class="container">
  <h3>To do items</h3>

  <table class="table table-striped">
    <tr>
      <th>Title</th>
      <th>Due date</th>
    </tr>

    <% @tenant.todo_items.each do |item| %>
        <tr>
          <td><%= item.title %></td>
          <td><%= item.due_date %></td>
        </tr>
    <% end %>
  </table>

  <br />
  <br />

  <%= link_to 'Other Participants', tenants_path, {:class =>"btn btn-default"} %>

  <br />
  <br />
</div>

todo-rails/app/views/todo/index.html.erb
<div class="container">

  <h1>Make your own To do list</h1>

  <br />
  <br />

  <%= link_to 'Create account', new_tenant_path, {:class=>"btn btn-lg btn-success"} %>
</div>

todo-rails/app/views/todo_items/_form.html.erb
<%= form_for @todo_item do |f| %>

    <% if @todo_item.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@todo_item.errors.count, "error") %> prohibited
            this to do item from being saved:
          </h2>
          <ul>
            <% @todo_item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :due_date %><br>
      <%= f.text_field :due_date%>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

todo-rails/app/views/todo_items/edit.html.erb
<h1>Editing To do item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_items_path %>

todo-rails/app/views/todo_items/index.html.erb
<h1>My To do list</h1>

<%= link_to 'Add to do item', new_todo_item_path %>
<br />
<br />

<table>
  <tr>
    <th>Title</th>
    <th>Due date</th>
  </tr>

  <% @todo_items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.due_date %></td>
        <td><%= link_to 'Show', todo_item_path(item) %></td>
        <td><%= link_to 'Edit', edit_todo_item_path(item) %></td>
        <td><%= link_to 'Destroy', todo_item_path(item),
                method: :delete,
                data: { confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

todo-rails/app/views/todo_items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_items_path %>

todo-rails/app/views/todo_items/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @todo_item.title %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todo_item.due_date %>
</p>

<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>